# Generated by Django 4.2.7 on 2023-12-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=10, help_text='Ваши попытки для преоброзования.', verbose_name='Попытка')),
                ('tuser', models.OneToOneField(help_text='Пользователь, который преобразовал текст.', on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка преоброзования',
                'verbose_name_plural': 'Попытки преоброзования',
            },
        ),
    ]
