# Generated by Django 4.2.7 on 2023-12-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_to_speech',
            name='file_name',
            field=models.CharField(help_text='Укажите имя аудиофайла.', max_length=200, verbose_name='Имя файла'),
        ),
    ]
